#!/usr/bin/env node

import { cp, mkdtemp, readdir, readFile, rename, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DEFAULT_OUTPUT = path.join(
	ROOT,
	"tools/cloudbox-deployer/internal/embedded/generated.go",
);

function fail(message) {
	throw new Error(`embed_cloudbox_artifact: ${message}`);
}

function parseArgs(argv) {
	let input = "";
	let output = DEFAULT_OUTPUT;
	for (let index = 0; index < argv.length; index += 1) {
		const argument = argv[index];
		const [name, inlineValue] = argument.split("=", 2);
		if (name !== "--input" && name !== "--output") fail(`不支持的参数：${argument}`);
		const value = inlineValue ?? argv[++index];
		if (!value) fail(`缺少参数值：${name}`);
		if (name === "--input") input = path.resolve(process.cwd(), value);
		if (name === "--output") output = path.resolve(process.cwd(), value);
	}
	if (!input) fail("必须提供 --input <artifact-directory>");
	return { input, output };
}

async function collectFiles(root) {
	const files = [];
	async function visit(current, relativeDirectory = "") {
		for (const entry of await readdir(current, { withFileTypes: true })) {
			if (entry.isSymbolicLink()) fail(`artifact 不允许 symlink：${entry.name}`);
			const relative = path.join(relativeDirectory, entry.name);
			const absolute = path.join(current, entry.name);
			if (entry.isDirectory()) {
				await visit(absolute, relative);
				continue;
			}
			if (!entry.isFile()) fail(`artifact 包含非普通文件：${relative}`);
			files.push({
				name: relative.split(path.sep).join("/"),
				content: await readFile(absolute),
			});
		}
	}
	await visit(root);
	files.sort((left, right) => left.name.localeCompare(right.name));
	return files;
}

function goString(value) {
	return JSON.stringify(value);
}

async function main() {
	const { input, output } = parseArgs(process.argv.slice(2));
	const inputInfo = await stat(input).catch(() => null);
	if (!inputInfo?.isDirectory()) fail(`输入目录无效：${input}`);
	const files = await collectFiles(input);
	if (!files.some((file) => file.name === "manifest.json"))
		fail("artifact 缺少 manifest.json");
	const lines = [
		"// Code generated by scripts/embed_cloudbox_artifact.mjs; DO NOT EDIT.",
		"package embedded",
		"",
		"import \"encoding/base64\"",
		"",
		"func init() {",
		"\tFiles = map[string][]byte{",
	];
	for (const file of files) {
		lines.push(`\t\t${goString(file.name)}: mustDecode(${goString(file.content.toString("base64"))}),`);
	}
	lines.push("\t}", "}", "", "func mustDecode(value string) []byte {", "\tdecoded, err := base64.StdEncoding.DecodeString(value)", "\tif err != nil {", "\t\tpanic(err)", "\t}", "\treturn decoded", "}", "");
	const parent = path.dirname(output);
	const staging = await mkdtemp(path.join(parent, ".embedded-"));
	const temporary = path.join(staging, path.basename(output));
	try {
		await writeFile(temporary, lines.join("\n"), { mode: 0o600 });
		await rename(temporary, output);
	} finally {
		await rm(staging, { recursive: true, force: true }).catch(() => {});
	}
	process.stdout.write(`已生成单文件内嵌源文件：${output}（${files.length} 个文件，${files.reduce((total, file) => total + file.content.length, 0)} 字节）\n`);
}

main().catch((error) => {
	process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
	process.exitCode = 1;
});
